services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: rag_pgvector
    environment:
      POSTGRES_DB: ragdb
      POSTGRES_USER: raguser
      POSTGRES_PASSWORD: ragpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U raguser -d ragdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag_app
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      PGVECTOR_CONNECTION: postgresql+psycopg://raguser:ragpass@postgres:5432/ragdb
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    # Expose for debugging — change back to just 'expose: ["8000"]' later
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    restart: unless-stopped

  consumer:
    build: .
    depends_on:
      kafka:
        condition: service_started
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      PGVECTOR_CONNECTION: postgresql+psycopg://raguser:ragpass@postgres:5432/ragdb
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    volumes:
      - ./:/app
    restart: unless-stopped
    command: ["python", "consumer.py"]

  frontend:
    build:
      context: ./rag-frontend
      dockerfile: Dockerfile
    container_name: rag_frontend
    depends_on:
      - app
    ports:
      - "3000:80"
    restart: unless-stopped
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: rag_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: unless-stopped
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: rag_kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    restart: unless-stopped
volumes:
  pgdata: